name: Build and Push Spring Boot Docker Image

on:
  push:
    branches:
      - main  # Thay đổi nếu bạn muốn workflow chạy trên nhánh khác
  pull_request:
    branches:
      - main

jobs:
  build_src:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package -DskipTests

      
    - name: Log in to dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push image to Docker Hub
    
      uses: docker/build-push-action@v3
        # Sử dụng action "docker/build-push-action" để đẩy image lên Docker Hub
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/panda-tool:${{ github.sha }}
# Job 2: Deploy
  deploy:
    needs: build_src
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
       # Sử dụng action "appleboy/ssh-action" để triển khai image lên server thông qua SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/panda-tool:${{ github.sha }}

            docker stop panda-tool
            docker rm panda-tool 

            docker run -d -p 8888:3000 --name panda-tool ${{ secrets.DOCKERHUB_USERNAME }}/panda-tool:${{ github.sha }}
